ALTER TABLE users
ADD COLUMN IF NOT EXISTS leader_status VARCHAR(20),
ADD COLUMN IF NOT EXISTS is_onboarding_complete BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS suburb VARCHAR(100),
ADD COLUMN IF NOT EXISTS province VARCHAR(100),
ADD COLUMN IF NOT EXISTS country VARCHAR(100);
