export const ZIM_CHURCHES = [
  "Apostolic Faith Mission in Zimbabwe (AFM)",
  "Zimbabwe Assemblies of God Africa (ZAOGA)",
  "United Family International Church (UFIC)",
  "Prophetic Healing and Deliverance (PHD) Ministries",
  "Celebration Ministries International",
  "Zion Christian Church (ZCC)",
  "African Apostolic Church (Johane Marange)",
  "Johane Masowe Apostles",
  "First Ethiopian Church of Zimbabwe",
  "Christian Marching Church",
  "Roman Catholic Church",
  "Anglican Church",
  "Methodist Church in Zimbabwe",
  "African Methodist Church",
  "African Methodist Episcopal Church",
  "United Methodist Church",
  "Reformed Church in Zimbabwe",
  "Church of Central Africa Presbyterian",
  "United Congregational Church of Southern Africa",
  "Uniting Presbyterian Church of Southern Africa",
  "United Church of Christ in Zimbabwe",
  "Evangelical Lutheran Church in Zimbabwe",
  "Salvation Army",
  "Baptist Convention of Zimbabwe",
  "Baptist Union of Zimbabwe",
  "Central Baptist Church",
  "Ebenezer Baptist Church",
  "Seventh-day Adventist Church",
  "Brethren in Christ Church",
  "New Apostolic Church",
  "Agape Missions",
  "Victory Fellowship Church",
  "Jehovah's Witnesses",
  "Heartfelt International Ministries",
  "Harvest House International",
  "Word of Life International Ministries",
  "Faith Ministries",
  "New Life Covenant Church",
  "Christ Embassy Zimbabwe",
  "Christ Connect Family Church (CCFC)",
  "Lighthouse Chapel International",
  "Church of Christ",
  "Zimbabwe Council of Churches (ZCC Umbrella)",
  "Evangel Fellowship of Zimbabwe (EFZ Umbrella)",
  "Zimbabwe Catholic Bishops' Conference (ZCBC Umbrella)",
];
